### PR TITLE
Migrate badwolf drivers to go modules and use Github actions for continuous testing and move boltdb to the maintained version

### PR DESCRIPTION
**Pull request by aerostitch**
A similar work has been done on the Badwolf project this project depends on.

Note that I had to use badwolf@master when setting up the go module as the number of arguments in the tools/common.Run arguments has changed after the latest release (over 3 years go, maybe time to cut a new release?).

### CODE REVIEW

**Comment by aerostitch** [comment]
Note that it currently fails when you ad the `-race` with the following:

```
$ go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
?       github.com/google/badwolf-drivers/bw    [no test files]
=== RUN   TestGraphManipulation
fatal error: checkptr: unsafe pointer conversion

goroutine 20 [running]:
runtime.throw(0x69b13a, 0x23)
        /usr/lib/go-1.14/src/runtime/panic.go:1116 +0x72 fp=0xc00004c740 sp=0xc00004c710 pc=0x4657a2
runtime.checkptrAlignment(0xc0001620b0, 0x677540, 0x1)
        /usr/lib/go-1.14/src/runtime/checkptr.go:20 +0xc9 fp=0xc00004c770 sp=0xc00004c740 pc=0x438609
github.com/boltdb/bolt.(*Bucket).write(0xc00004c8e8, 0x0, 0x0, 0x0)
        /home/herlantj/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:626 +0x15c fp=0xc00004c7d8 sp=0xc00004c770 pc=0x5cecac
github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc000178018, 0xc0001243a8, 0x6, 0x6, 0xffffffffffffffff, 0xc00004c9f0, 0x43eb98)
        /home/herlantj/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:188 +0x465 fp=0xc00004c998 sp=0xc00004c7d8 pc=0x5cbd85
github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc000178018, 0xc0001243a8, 0x6, 0x6, 0x2, 0xc000178000, 0xc0ffffffff)
        /home/herlantj/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:206 +0x5e fp=0xc00004ca00 sp=0xc00004c998 pc=0x5cc12e
github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(...)
        /home/herlantj/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:115
github.com/google/badwolf-drivers/bwbolt.New.func1(0xc000178000, 0xc00011c901, 0xc000178000)
        /home/herlantj/git/aerostitch/badwolf-drivers/bwbolt/bolt.go:56 +0xdf fp=0xc00004cab8 sp=0xc00004ca00 pc=0x627fdf
github.com/boltdb/bolt.(*DB).Update(0xc000172000, 0xc00004cbf8, 0x0, 0x0)
        /home/herlantj/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:598 +0xec fp=0xc00004cb60 sp=0xc00004cab8 pc=0x5d70fc
github.com/google/badwolf-drivers/bwbolt.New(0xc000120090, 0x2a, 0x6d2e80, 0x85a148, 0xb2d05e00, 0xc000120000, 0x25, 0x27, 0xcf84e, 0x5609fc, ...)
        /home/herlantj/git/aerostitch/badwolf-drivers/bwbolt/bolt.go:55 +0x2a3 fp=0xc00004cc40 sp=0xc00004cb60 pc=0x61f8f3
github.com/google/badwolf-drivers/bwbolt.testDriver(0xc00016c120, 0xc000102900, 0x2, 0xc00011f398)
        /home/herlantj/git/aerostitch/badwolf-drivers/bwbolt/bolt_test.go:34 +0x2de fp=0xc00004cd78 sp=0xc00004cc40 pc=0x62419e
github.com/google/badwolf-drivers/bwbolt.TestGraphManipulation(0xc00016c120)
        /home/herlantj/git/aerostitch/badwolf-drivers/bwbolt/bolt_test.go:43 +0x74 fp=0xc00004ced0 sp=0xc00004cd78 pc=0x624334
testing.tRunner(0xc00016c120, 0x69fb70)
        /usr/lib/go-1.14/src/testing/testing.go:1039 +0x1ec fp=0xc00004cfd0 sp=0xc00004ced0 pc=0x560b9c
runtime.goexit()
        /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004cfd8 sp=0xc00004cfd0 pc=0x4974d1
created by testing.(*T).Run
        /usr/lib/go-1.14/src/testing/testing.go:1090 +0x701

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00016c000, 0x6973f8, 0x15, 0x69fb70, 0x0)
        /usr/lib/go-1.14/src/testing/testing.go:1091 +0x739
testing.runTests.func1(0xc00016c000)
        /usr/lib/go-1.14/src/testing/testing.go:1334 +0xa7
testing.tRunner(0xc00016c000, 0xc000133cd0)
        /usr/lib/go-1.14/src/testing/testing.go:1039 +0x1ec
testing.runTests(0xc00013c140, 0x82bd80, 0x4, 0x4, 0x0)
        /usr/lib/go-1.14/src/testing/testing.go:1332 +0x528
testing.(*M).Run(0xc00016a000, 0x0)
        /usr/lib/go-1.14/src/testing/testing.go:1249 +0x440
main.main()
        _testmain.go:98 +0x338

goroutine 19 [chan send]:
github.com/google/badwolf/triple/node.init.0.func1()
        /home/herlantj/go/pkg/mod/github.com/google/badwolf@v0.9.1-0.20201026105356-73451a945c65/triple/node/node.go:216 +0x6a
created by github.com/google/badwolf/triple/node.init.0
        /home/herlantj/go/pkg/mod/github.com/google/badwolf@v0.9.1-0.20201026105356-73451a945c65/triple/node/node.go:214 +0x2c1
FAIL    github.com/google/badwolf-drivers/bwbolt        0.033s
FAIL

```

Give me a few minutes to fix that.

**Comment by aerostitch** [comment]
The above error is an error that comes with Go 1.14 and comes from the bolt package we use.

Note that this package has been archived for several years as it is now unmaintained, see: https://github.com/boltdb/bolt/commit/fa5367d20c994db73282594be0146ab221657943

Should we switch to the newer version now maintained by etcd? https://github.com/etcd-io/bbolt

They fixed that issue in there already: https://github.com/etcd-io/bbolt/commit/543c40ab4152935b36df4fba524e741046a359d4#diff-e3921acdcbbc7f28fb6b5cb074e8ff534b1b63ec9fc6ec6e3a14322ab85d5f94

@xllora

**Comment by aerostitch** [comment]
The last commit moves the version of boltdb to the version supported by etcd. Let me know what you think.

**Comment by xllora** [comment]
Yes, that sounds like the right thing to do here since the fork focus on maintainability.

**Pull request merged**
